### PR TITLE
default value

### LINKED ISSUE #270: submit without change form saves null
cambodia_arena_test
> cluster inventory year

when a wrong entry (2014), and when in edit mode click “Save and return again”, value will disappear

### PR DESCRIPTION
**Pull request by ramirobg94**
fixes #270

### CODE REVIEW

File: src/form/Attributes/common/BaseInput/Form/index.js [hunk 1]
```diff
@@ -34,8 +34,8 @@ const Form = ({nodeDef, keyboardType = 'default'}) => {
         nodeDef.type === NodeDefType.text
           ? transform({
               transformFunction: NodeDefs.getTextTransform(nodeDef),
-            })(newValue)
-          : Number((newValue || '').replace(',', '.'));
+            })(newValue || String(node.value || ''))
+          : Number((newValue || String(node.value || '')).replace(',', '.'));
```
Comment (SteRiccio) [inline src/form/Attributes/common/BaseInput/Form/index.js]: I see some duplication here... Can it be extracted to a variable to make this part more clear?

**Review by SteRiccio — APPROVED** [review]
