### PR TITLE
Bug/282 transform  coordinates srs

### LINKED ISSUE #282: SRS ->. convert coordinates using arena-core https://github.com/openforis/arena-core/blob/26a97e59595f1f0f4b59e01d607ed0cdc8432688/src/geo/points/transform.ts

### PR DESCRIPTION
**Pull request by ramirobg94**
fixes #282

### CODE REVIEW

File: src/form/Attributes/Coordinate/Form/index.js [hunk 1]
```diff
@@ -53,10 +61,12 @@ const Form = ({nodeDef}) => {
   const handleSelect = useCallback(
     srs => {
       if (srs?.code) {
-        handleUpdateValue('srs')(srs.code);
+        setValue(prevValue =>
+          Points.transform(PointFactory.createInstance(prevValue), srs?.code),
```
Comment (SteRiccio) [inline src/form/Attributes/Coordinate/Form/index.js:65]: PrevValue should be already a point object, right?!

**Review by SteRiccio — APPROVED** [review]
