### PR TITLE
Fix multiple entity home keys visibility 

### LINKED ISSUE #599: multiple entity summary view: strange behaviour after item deletion
it happens when the entity has more than one key attributes; first only one key appears in the table; when an item is deleted, both keys appear.

https://github.com/user-attachments/assets/96e6fd4a-993c-4324-b59f-bffe355fd234

### PR DESCRIPTION
**Pull request by ramirobg94**
resolves #599

### CODE REVIEW

File: src/state/form/selectors/index.js [hunk 1]
```diff
@@ -423,6 +423,10 @@ const getFormAttributesNodeDefs = createSelector(
     formAttributesNodeDefs = formAttributesNodeDefs
       ?.map(nodeDefUuid => nodeDefsByUuid[nodeDefUuid])
       .filter(_nodeDef => {
+        if (NodeDefs.isKey(_nodeDef)) {
+          return true;
+        }
+
```
Comment (SteRiccio) [inline src/state/form/selectors/index.js]: the check Objects.isEmpty(_nodeDef) could be done first, then all other checks.
Please also notice that there are helper methods in Nodes to extract other properties, like Nodes.isHidden, Nodes.isHiddenInMobile.

**Review by SteRiccio — CHANGES_REQUESTED** [review]

File: src/state/form/selectors/index.js (hunk 1 above)
Comment (ramirobg94) [reply src/state/form/selectors/index.js]: if (Objects.isEmpty(_nodeDef)) { return false; }
if (NodeDefs.isKey(_nodeDef)) { return true; }
if (_nodeDef?.props?.hidden) { return false; }
if (NodeDefs.isHiddenInMobile(cycle)(_nodeDef)){ return false; }

File: src/state/form/selectors/index.js [hunk 2]
```diff
@@ -423,6 +423,10 @@ const getFormAttributesNodeDefs = createSelector(
...
         if (Objects.isEmpty(_nodeDef)) {
           return false;
         }
```
Comment (ramirobg94) [inline src/state/form/selectors/index.js]:
```suggestion
        if (Objects.isEmpty(_nodeDef)) {
          return false;
        }
```
```suggestion
```

File: src/state/form/selectors/index.js [hunk 3]
```diff
@@ -423,6 +423,10 @@ const getFormAttributesNodeDefs = createSelector(
     formAttributesNodeDefs = formAttributesNodeDefs
       ?.map(nodeDefUuid => nodeDefsByUuid[nodeDefUuid])
       .filter(_nodeDef => {
+        if (NodeDefs.isKey(_nodeDef)) {
+          return true;
+        }
```
Comment (ramirobg94) [inline src/state/form/selectors/index.js]:
```suggestion
        if (Objects.isEmpty(_nodeDef)) {
          return false;
        }
        
        if (NodeDefs.isKey(_nodeDef)) {
          return true;
        }
```

**Review by SteRiccio — APPROVED** [review]

File: src/state/form/selectors/index.js [hunk 4]
```diff
@@ -426,13 +426,16 @@ const getFormAttributesNodeDefs = createSelector(
...
+
         if (_nodeDef?.props?.hidden) {
           return false;
         }
 
-        const layoutProps = NodeDefs.getLayoutProps(cycle)(_nodeDef);
-
-        if (layoutProps?.hiddenInMobile === true) {
+        if (NodeDefs.isHiddenInMobile(cycle)(_nodeDef)) {
```
Comment (SteRiccio) [inline src/state/form/selectors/index.js:438]: NodeDefs.isHidden can be used here instead of _nodeDef?.props?.hidden

File: src/state/form/selectors/index.js [hunk 5]
```diff
@@ -426,13 +426,16 @@ const getFormAttributesNodeDefs = createSelector(
         if (Objects.isEmpty(_nodeDef)) {
           return false;
         }
+
+        if (NodeDefs.isKey(_nodeDef)) {
+          return true;
+        }
+
         if (_nodeDef?.props?.hidden) {
```
Comment (ramirobg94) [inline src/state/form/selectors/index.js]:
```suggestion
        if (NodeDefs.isHidden(_nodeDef)) {
```

**Review by SteRiccio — APPROVED** [review]
