### PR TITLE
Bug/279 show x y in selected srs

### LINKED ISSUE #279: show x and y in the srs selected into the get location form

### PR DESCRIPTION
**Pull request by ramirobg94**
fixes #279

### CODE REVIEW

File: src/form/Attributes/Coordinate/Form/GetLocation/index.js [hunk 1]
```diff
@@ -10,7 +11,54 @@ import useGetLocation from '../useGetLocation';
 
 import styles from './styles';
 
-const GetLocation = ({handleSaveLocation}) => {
+const DEFAULT_SRS_CODE = '4326';
+
+const prepareItems = (location, {selectedSrs}) => {
+  console.log(location);
```
Comment (SteRiccio) [inline src/form/Attributes/Coordinate/Form/GetLocation/index.js:17]: maybe you forgot this

**Review by SteRiccio — APPROVED** [review]

File: src/form/Attributes/Coordinate/Form/GetLocation/index.js (hunk 1 above)
Comment (ramirobg94) [reply src/form/Attributes/Coordinate/Form/GetLocation/index.js:17]: yes

Comment (ramirobg94) [inline src/form/Attributes/Coordinate/Form/GetLocation/index.js:17]:
```suggestion
```
